# FastDFS客户端配置文件
# 跟踪服务器(Tracker Server)端口号
connect_timeout=30
network_timeout=60
charset=UTF-8
http.tracker_server_port=80

# 跟踪服务器(Tracker Server)地址
# 这里使用本地地址，端口号为22122
tracker_server=127.0.0.1:22122

# 存储服务器(Storage Server)端口号
storage_server_port=23000

# 组名
group_name=group1

# 存储路径
base_path=/tmp

# 上传文件大小限制
max_file_size=1048576000

# 连接池大小
connection_pool_max_idle_time=3600

# 日志级别
log_level=info

# 日志文件路径
log_filename=

# HTTP设置
http.anti_steal_token=no
http.secret_key=FastDFS1234567890
http.check_content_type=yes